# Security Policy Configuration
# This file defines the security policies for the Synapse Framework project

security:
  # Vulnerability Disclosure Policy
  disclosure:
    # How to report security vulnerabilities
    reporting:
      email: security@synapse-framework.dev
      url: https://github.com/synapse-framework/synapse/security/advisories/new
      pgp_key: "https://synapse-framework.dev/security/pgp-key.asc"
    
    # Response timeframes
    response:
      initial: "24 hours"
      resolution: "90 days"
      disclosure: "30 days after fix"
    
    # Supported versions
    supported_versions:
      - ">=0.3.0"
      - "main"
      - "develop"
  
  # Security Requirements
  requirements:
    # Code signing
    code_signing: true
    
    # Dependency scanning
    dependency_scanning: true
    
    # Secret scanning
    secret_scanning: true
    
    # Container scanning
    container_scanning: true
    
    # License compliance
    license_compliance: true
  
  # Security Headers
  headers:
    - "X-Frame-Options: DENY"
    - "X-Content-Type-Options: nosniff"
    - "X-XSS-Protection: 1; mode=block"
    - "Strict-Transport-Security: max-age=31536000; includeSubDomains"
    - "Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'"
    - "Referrer-Policy: strict-origin-when-cross-origin"
    - "Permissions-Policy: geolocation=(), microphone=(), camera=()"
  
  # Security Scanning
  scanning:
    # Dependabot configuration
    dependabot:
      enabled: true
      frequency: "daily"
      severity_threshold: "moderate"
    
    # CodeQL configuration
    codeql:
      enabled: true
      languages: ["javascript", "typescript"]
      frequency: "weekly"
    
    # Snyk configuration
    snyk:
      enabled: true
      severity_threshold: "high"
      frequency: "daily"
  
  # Access Control
  access_control:
    # Repository access
    repository:
      admin: ["synapse-framework/security-team"]
      maintain: ["synapse-framework/core-team"]
      triage: ["synapse-framework/community-team"]
    
    # Branch protection
    branch_protection:
      main:
        required_reviews: 2
        required_status_checks: true
        enforce_admins: true
        restrictions: ["synapse-framework/core-team"]
      develop:
        required_reviews: 1
        required_status_checks: true
        enforce_admins: false
        restrictions: ["synapse-framework/core-team", "synapse-framework/community-team"]
  
  # Incident Response
  incident_response:
    # Escalation matrix
    escalation:
      level_1: "community-team"
      level_2: "core-team"
      level_3: "security-team"
    
    # Communication channels
    communication:
      internal: "security@synapse-framework.dev"
      public: "https://github.com/synapse-framework/synapse/security"
      status: "https://status.synapse-framework.dev"
  
  # Compliance
  compliance:
    # Standards
    standards:
      - "OWASP Top 10"
      - "CWE Top 25"
      - "NIST Cybersecurity Framework"
      - "ISO 27001"
    
    # Certifications
    certifications:
      - "SOC 2 Type II"
      - "ISO 27001"
      - "PCI DSS Level 1"