/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class EnvParser {
  static load(path?: string | undefined | null): Record<string, string>
  static parse(content: string): Record<string, string>
  static validate(schema: any): ValidationResult
}
export declare class ValidationResult {
  valid: boolean
  errors: Array<string>
  data: Record<string, any>
}
export declare class Validator {
  validatorType: string
  required?: boolean
  defaultValue?: any
  min?: number
  max?: number
  pattern?: string
}
