[package]
name = "snps-http-client-rust"
version = "0.1.0"
edition = "2021"
authors = ["Synapse Framework Team"]
description = "Zero-dependency high-performance HTTP client built with Rust"
license = "MIT"
repository = "https://github.com/synapse-framework/synapse"
homepage = "https://synapse.dev"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.16", features = ["full"] }
napi-derive = "2.16"
tokio = { version = "1.42", features = ["rt", "net", "io-util", "time", "macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2.5"
http = "1.0"
bytes = "1.0"
futures = "0.3"

[build-dependencies]
napi-build = "2.1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
opt-level = 0
debug = true