[package]
name = "synapse-cli"
version = "2.0.0"
edition = "2021"
authors = ["Synapse Framework Team"]
description = "🚀 The Ultimate Development CLI - 15+ powerful features including AI assistance, real-time collaboration, cloud sync, performance optimization, and much more!"

[[bin]]
name = "synapse"
path = "src/main.rs"

[dependencies]
criterion = { version = "0.5", features = ["async_tokio"] }
clap = { version = "4.4", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"
indicatif = "0.17"
console = "0.15"
dialoguer = "0.11"
dirs = "5.0"
walkdir = "2.3"
# git2 = "0.18"  # Commented out to avoid OpenSSL dependency
reqwest = { version = "0.11", features = ["json", "rustls-tls"], default-features = false }
uuid = { version = "1.0", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
regex = "1.10"
toml = "0.8"
yaml-rust = "0.4"
zip = "0.6"
tar = "0.4"
flate2 = "1.0"
sha2 = { version = "0.10", features = ["std"] }
hex = "0.4"
base64 = "0.21"
pprof = { version = "0.15.0", features = ["flamegraph", "protobuf"] }
dhat = { version = "0.3.3", optional = true }

[[bench]]
name = "my_benchmark"
harness = false